- name: Debug
  debug:
    msg: "{{ CONTAINERS_FOR_LOGS }}"

- name: Remove old logs directory
  file:
    path: "/opt/{{ CI_PROJECT_NAME }}/logs"
    state: absent

- name: Create logs directory
  file:
    path: "/opt/{{ CI_PROJECT_NAME }}/logs"
    state: directory

- name: Create logs
  shell: "docker logs {{ item }} &> /opt/{{ CI_PROJECT_NAME }}/logs/{{ item }}.log"
  args:
    executable: /bin/bash
  with_items: "{{ CONTAINERS_FOR_LOGS.split(' ') }}"
  ignore_errors: yes

- name: Copy logs directory from remote instance
  fetch:
    src:  "/opt/{{ CI_PROJECT_NAME }}/logs/{{ item }}.log"
    dest: "../logs/{{ inventory_hostname }}/"
    flat: yes
  with_items: "{{ CONTAINERS_FOR_LOGS.split(' ') }}"
  ignore_errors: yes