FROM node:19.8.1-alpine as builder
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY . .
RUN yarn build-storybook
                                  

FROM nginx:alpine as executor
COPY --from=builder /app/storybook-static /var/www/html/storybook-static
CMD ["nginx","-g","daemon off;"]