export enum ProfileActionTypes {
  SetState = 'PROFILE.SET_STATE',
  SetStateAccountInfo = 'PROFILE.SET_STATE_ACCOUNT_INFO',
  SetStatus = 'PROFILE.SET_STATUS',
  LinkWallet = 'PROFILE.LINK_WALLET',
  GetProfile = 'PROFILE.GET_PROFILE',
  DeleteWallet = 'PROFILE.DELETE_WALLET',
  UpdateProfile = 'PROFILE.UPDATE_PROFILE',
  UploadAvatar = 'PROFILE.UPLOAD_AVATAR',
  GetProfileUser = 'PROFILE.GET_PROFILE_USER',
  Notification = 'PROFILE.NOTIFICATION',
  NotificationSubscribe = 'PROFILE.NOTIFICATION_SUBSCRIBE',
  NotificationSubscribeUpdate = 'PROFILE.NOTIFICATION_SUBSCRIBE_UPDATE',
  NotificationMarkAsView = 'PROFILE.NOTIFICATION_MARK_AS_VIEW',
}
