export enum ProfileActionTypes {
  SetState = 'PROFILE.SET_STATE',
  SetStateAccountInfo = 'PROFILE.SET_STATE_ACCOUNT_INFO',
  SetStateRequester = 'PROFILE.SET_STATE_REQUESTER',
  SetStatusRequester = 'PROFILE.SET_STATUS_REQUESTER',
  SetStatus = 'PROFILE.SET_STATUS',
  LinkWallet = 'PROFILE.LINK_WALLET',
  GetProfile = 'PROFILE.GET_PROFILE',
  DeleteWallet = 'PROFILE.DELETE_WALLET',
  UpdateProfile = 'PROFILE.UPDATE_PROFILE',
  UploadAvatar = 'PROFILE.UPLOAD_AVATAR',
  GetProfileUser = 'PROFILE.GET_PROFILE_USER',
  Notification = 'PROFILE.NOTIFICATION',
  NotificationSubscribe = 'PROFILE.NOTIFICATION_SUBSCRIBE',
  NotificationMarkAsView = 'PROFILE.NOTIFICATION_MARK_AS_VIEW',
  CreateApiKey = 'PROFILE.CREATE_API_KEY',
  GetApiKey = 'PROFILE.GET_API_KEY',
  DeleteApiKey = 'PROFILE.DELETE_API_KEY',
}
